In [71]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [72]:
df=pd.read_csv("breast_cancer.csv")

In [73]:
df.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [74]:
df.shape

(683, 11)

In [75]:
df.drop(columns=["Sample code number"] ,inplace=True)

In [76]:
df.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2

In [77]:
df.shape

(683, 10)

In [78]:
X_train, X_test ,y_train ,y_test =train_test_split(df.iloc[ : , :-1] ,df.iloc[ : , -1],test_size=0.2)

In [79]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [80]:
X_train

array([[ 2.02633098,  0.99587592,  0.99617913, ...,  2.41372468,
         1.45325829, -0.33067736],
       [ 0.58103155,  2.33763596,  1.33955906, ...,  1.98955549,
         2.4797512 ,  0.27723455],
       [ 2.02633098,  0.99587592,  0.30941928, ...,  2.41372468,
         2.4797512 , -0.33067736],
       ...,
       [ 2.02633098, -0.0104441 ,  0.30941928, ...,  0.29287873,
        -0.59972755, -0.33067736],
       [ 2.02633098,  0.32499591, -0.03396065, ...,  1.14121711,
         0.76892968,  0.27723455],
       [-0.50294303, -0.68132412, -0.72072051, ..., -0.55545965,
         0.08460106, -0.33067736]], shape=(546, 9))

In [81]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)

In [82]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [83]:
X_train_tensor.shape

torch.Size([546, 9])

In [85]:
y_train_tensor = (y_train_tensor == 4).float()
y_test_tensor = (y_test_tensor == 4).float()

In [86]:
y_train_tensor

tensor([1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0.,
        0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
        1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
        1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 1., 1., 0.])

In [87]:
from torch.utils.data import Dataset, DataLoader

In [88]:
class CustomDataset(Dataset):

    def __init__(self,features,labels):
        self.features = features
        self.labels = labels

    def __len__(self):

        return len(self.features)

    def __getitem__(self, idx):

        return self.features[idx], self.labels[idx]

In [89]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [90]:
train_dataset[10]

(tensor([-1.2256, -0.6813, -0.7207, -0.6197, -0.5247, -0.6847, -0.9796, -0.5997,
         -0.3307]),
 tensor(0.))

In [91]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [92]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [93]:
learning_rate = 0.1
epochs = 25

In [94]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [95]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5868968963623047
Epoch: 2, Loss: 0.09962835907936096
Epoch: 3, Loss: 0.06515556573867798
Epoch: 4, Loss: 0.2658291459083557
Epoch: 5, Loss: 0.037471991032361984
Epoch: 6, Loss: 0.014433865435421467
Epoch: 7, Loss: 0.048759106546640396
Epoch: 8, Loss: 0.04332856088876724
Epoch: 9, Loss: 0.13658104836940765
Epoch: 10, Loss: 0.03891004994511604
Epoch: 11, Loss: 0.021911557763814926
Epoch: 12, Loss: 0.009177467785775661
Epoch: 13, Loss: 0.003930165898054838
Epoch: 14, Loss: 0.03384825587272644
Epoch: 15, Loss: 0.005324154626578093
Epoch: 16, Loss: 0.014574231579899788
Epoch: 17, Loss: 0.025327425450086594
Epoch: 18, Loss: 0.0057507846504449844
Epoch: 19, Loss: 0.009427017532289028
Epoch: 20, Loss: 1.3152012825012207
Epoch: 21, Loss: 0.022374797612428665
Epoch: 22, Loss: 0.020307831466197968
Epoch: 23, Loss: 0.02071955054998398
Epoch: 24, Loss: 0.00546250119805336
Epoch: 25, Loss: 0.01967417448759079

In [96]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9750